variable "rg-name" {}
variable "project_name" {}
variable "vnet_cidr" {}
variable "web_subnet_cidr" {}
variable "app_subnet_cidr" {}
variable "db_subnet_cidr" {}
variable "vm_size" {}
variable "user" {}
variable "password" {}
